- platform: wake_on_lan
  mac:  !secret desktop_mac
  name: "Desktop Power"
  host: 192.168.1.127
  #broadcast_port: 9
  broadcast_address: 192.168.1.255
  turn_off:
    service: shell_command.sleep_on_lan
  
