#Turn on the living room lights 5min after sunrise
- alias: "Sun up living room lights"
  trigger:
    platform: sun
    event: sunrise
    offset: "+00:05:00"
  action:
    service: switch.turn_on
    entity_id: group.livingroom
    
#Turn on the inside lights 1HR before sunset
- alias: "Sun down inside lights"
  trigger:
    platform: sun
    event: sunset
    offset: "-01:0:00"
  action:
    service: switch.turn_on
    data:
      entity_id: 
        - group.livingroom
        - switch.bedroom_lamp
         - switch.office

#Set thermostats to home when @ Home
- alias: "Set Thermostats to Home"
  initial_state: true
  trigger: 
    platform: state
    entity_id: device_tracker.greg_samsunggalaxys8
    
  condition:
    condition: state
    entity_id: device_tracker.greg_samsunggalaxys8
    state: 'home'
  
  action:
    - service: climate.set_preset_mode
      data:
        entity_id: climate.upstairs
        preset_mode: 'Home'
 
    - service: climate.set_preset_mode
      data:
        entity_id: climate.downstairs
        preset_mode: 'Home' 
       
  