- alias: Set Theme
  trigger:
    - platform: state
      entity_id: sun.sun
      to: above_horizon
    - platform: state
      entity_id: sun.sun
      to: below_horizon
  action:
    service_template: frontend.set_theme
    data_template:
      name: >
        {% if states.sun.sun.state == "above_horizon" %}
          {{ "default" }}
        {% else %}
          {{ "Google Dark Theme" }}
        {% endif %}
        
#  - alias: 'Vacation mode auto set'
#    initial_state: 'on'
#    trigger:
#      platform: state
#      entity_id: group.persons
#      from: 'home'
#      to: 'not_home'
#      for: '24:00:00'
#    condition:
#      - condition: state
#        entity_id: input_boolean.guest_mode
#        state: "off"
#    action:
#      - service: input_boolean.turn_on
#        entity_id: input_boolean.vacation_mode
#      - service: notify.telegram_notify_Greg
#        data:
#          message: "No one at home for 24 hours, switching on vacation mode."