#Update Weather Sensors
- alias: 'Update Weather Sensors'
  initial_state: true
  trigger:
    platform: time_pattern
    hours: "/1"
  action:
  - service: homeassistant.update_entity
    entity_id:
      - sensor.forecast_0
      - sensor.forecast_1
      - sensor.forecast_2
      - sensor.forecast_3
      - sensor.forecast_4
      - sensor.forecast_5
      - sensor.forecast_6
      - sensor.forecast_7
      - sensor.sunset
      - sensor.sunrise
      - sensor.daylight
    
- alias: 'Garage Open Notification'
  initial_state: true
  trigger: 
    platform: state
    entity_id: binary_sensor.garage_door_opened 
    to: 'on'
    for:
      minutes: 5
  action:
    - service: notify.telegram_notify_Greg
      data:
        message: 'The Garage Door has been open for more than 5 minutes'
    - service: notify.telegram_notify_Sara
      data:
        message: 'The Garage Door has been open for more than 5 minutes'

- alias: "NUT UPS Error"
  initial_state: true
  trigger:
    platform: state
    entity_id: sensor.ups_status
    to: unavailable
    for:
      minutes: 5
  action:
    - service: notify.telegram_notify_Greg
      data:
        message: 'The UPS is in an unknown state, you may need to reboot the server.'
  
- alias: "Reload Speedtest"
  initial_state: true
  trigger:
    - platform: template
      value_template: >-
        {% set last_updated = as_timestamp(states.sensor.speedtest_download.last_updated) %}
        {% set is_unavailable = states.sensor.speedtest_download.last_updated == 'unavailable' %}
        {% if (as_timestamp(now()) - last_updated) > 3900 or is_unavailable == 'True'%}
          true
        {% else %}
          false
        {% endif %}
  action:
    - service: notify.telegram_notify_Greg
      data:
        message: >-
          Speedtest was last loaded {{relative_time(states.sensor.speedtest_download.last_updated) }}
          ago. It is being reloaded.
    - delay: "00:00:03"
    - service: homeassistant.reload_config_entry
      data:
        entry_id: 5381213a762e2b7528453d58d26ba12c
      target:
        entity_id: sensor.speedtest_download