- alias: 'Morning Weather'
  trigger: 
    platform: time
    at: "06:44:00"
  action:
    - service: notify.telegram_notify_greg
      data: 
        message: "Today's forecast calls for {{state_attr('weather.krdu_daynight', 'forecast')[0].detailed_description}}
                  \n Humidity: {{states('sensor.krdu_relative_humidity')}}% 
                  \n Dewpoint: {{states('sensor.krdu_dew_point')}} deg F 
                  \n Sunrise: {{states.sensor.sunrise.state}}AM 
                  \n Sunset: {{states.sensor.sunset.state}}PM"


- alias: 'qBitTorrent Down Notification'
  trigger:
    - platform: state
      entity_id: sensor.qbittorrent_status
      to: 'unavailable'
      for:
        seconds: 60
  action:
    - service: notify.telegram_notify_greg
      data:
        title: "*qBitTorrent is Down*"
        message: "qBitTorrent has lost connection, log on to restart it"


- id: "3dbc90c3-6d28-4ba4-8c4e-0efaa3cb6160"
  alias: Update Available Notification
  trigger:
    - platform: state
      entity_id: binary_sensor.docker_hub_update_available
      from: 'off'
      to: 'on'
  action:
    - service: notify.telegram_notify_greg
      data:
        message: "Home Assistant {{states('sensor.docker_hub')}} is available."

- id: "277eee6a-72fb-47b9-a73d-0d24721e80f4"
  alias: Version Check
  trigger: 
    platform: event
    event_type: telegram_command
    event_data:
      command: '/version'
  action: 
    - service: telegram_bot.send_message
      data: 
        chat_id: '{{ trigger.event.data.chat_id }}'
        message: "The current version is {{states('sensor.docker_hub')}},
                  {% if states('binary_sensor.docker_hub_update_available') == 'on'%} You are not up to date
            {% else %} You are up to date
            {% endif %}"

- id: "47569aa4-4fca-417e-b73b-5e02a302d71e"
  alias: Trash Check
  trigger: 
    platform: event
    event_type: telegram_command
    event_data:
      command: '/garbage'
  action: 
    - service: telegram_bot.send_message
      data: 
        chat_id: '{{ trigger.event.data.chat_id }}'
        message: >-
          This week's pickup is:
          {% set calendar = 'calendar.712_cross_timbers_dr_durham' %}
          {% set start = as_timestamp(state_attr(calendar,'start_time'))|timestamp_custom('%B %-d %Y', 'true') %}
          {% if 'Household' in state_attr('calendar.712_cross_timbers_dr_durham', 'message') and 
                states('calendar.712_cross_timbers_dr_durham') == 'on' %}
          {{"Trash on " + start}}
          {% else %}
          {% if 'Recycling' in state_attr('calendar.712_cross_timbers_dr_durham', 'message') and 
                states('calendar.712_cross_timbers_dr_durham') == 'on' %}
          {{"Recycling on "+ start}}
          {% endif %}
          {% endif %}
