#Thermostat Automations

#Set thermostats to home when @ Home
- alias: "Set Thermostats to Home"
  initial_state: true
  trigger: 
    - platform: state
      entity_id: 
        - person.greg
        - person.sara
  condition:
    condition: and
    conditions:
      - condition: time 
        after: '08:00:00'
        before: '17:00:00'
        weekday:
          - mon
          - tue
          - wed
          - thu
          - fri
      - condition: or
        conditions:
          - condition: state
            entity_id: person.greg
            state: 'home'
          - condition: state
            entity_id: person.sara
            state: 'home'

  action:
    - service: climate.set_preset_mode
      data:
        entity_id: 
          - climate.upstairs
          - climate.downstairs
        preset_mode: 'Home'

#Set thermostats to Away when !@ Home
- alias: "Set Thermostats to Away"
  initial_state: true
  trigger: 
    - platform: state
      entity_id: 
        - person.greg
        - person.sara

  condition:
    condition: and
    conditions:
      - condition: time 
        after: '08:00:00'
        before: '17:00:00'
        weekday:
          - mon
          - tue
          - wed
          - thu
          - fri
      - condition: template
        value_template: "{{ not is_state('person.greg','home') }}"
      - condition: state
        entity_id: person.sara
        state: 'not_home'
      - condition: state
        entity_id: input_boolean.guest_mode
        state: 'off'
  action:
    - service: climate.set_preset_mode
      data:
        entity_id:
          - climate.downstairs
          - climate.upstairs
        preset_mode: 'Away'

- alias: "Thermostat Break"
  initial_state: false  
  trigger:
    platform: template
    value_template: "{% if state_attr('climate.upstairs', 'hvac_action')=='cooling' %}true{% endif %}"
    for: '01:00:00'
  action:
    - service: automation.turn_off
      target:
        entity_id: automation.set_thermostats_to_home
    - service: climate.set_hvac_mode
      target:
        entity_id: climate.upstairs
      data:
        hvac_mode: 'off'
    - service: climate.set_fan_mode
      target: 
        entity_id: climate.upstairs
      data:
        fan_mode: 'on'
    - service: climate.set_hvac_mode
      target:
        entity_id: climate.downstairs
      data:
        hvac_mode: 'off'
    - service: climate.set_fan_mode
      target: 
        entity_id: climate.downstairs
      data:
        fan_mode: 'on'

    - delay: "00:10:00"
    - service: automation.turn_on
      target:
        entity_id: automation.set_thermostats_to_home
    - service: climate.set_hvac_mode
      target:
        entity_id: climate.upstairs
      data:
        hvac_mode: 'cool'
    - service: climate.set_fan_mode
      target: 
        entity_id: climate.upstairs
      data:
        fan_mode: 'auto'
    - service: climate.set_hvac_mode
      target:
        entity_id: climate.downstairs
      data:
        hvac_mode: 'cool'
    - service: climate.set_fan_mode
      target: 
        entity_id: climate.downstairs
      data:
        fan_mode: 'auto'


- alias: Thermostat Vacation Hold
  initial_state: true
  trigger:
    platform: state
    entity_id: input_boolean.vacation_mode
    from: 'off'
    to: 'on'
  action:
    - service: ecobee.create_vacation
      data:
        entity_id: climate.upstairs
        vacation_name: "UpstairsHold"
        cool_temp: 78
        heat_temp: 65
        fan_mode: auto
        fan_min_on_time: 5
    - service: ecobee.create_vacation
      data:
        entity_id: climate.downstairs
        vacation_name: "DownstairsHold"
        cool_temp: 78
        heat_temp: 65
        fan_mode: auto
        fan_min_on_time: 5

- alias: Thermostat Vacation End
  initial_state: true
  trigger:
    platform: state
    entity_id: input_boolean.vacation_mode
    from: 'on'
    to: 'off'
  action:
    - service: ecobee.delete_vacation
      data_template:
        entity_id: climate.upstairs
        vacation_name: "UpstairsHold"
    - service: ecobee.delete_vacation
      data_template:
        entity_id: climate.upstairs
        vacation_name: "DownstairsHold"


- alias: Thermostat Override
  initial_state: true
  trigger:
    - platform: template
      value_template: >-
        {% set upstairs_mode = state_attr('climate.upstairs', 'preset_mode') %}
        {% set downstairs_mode = state_attr('climate.downstairs', 'preset_mode') %}
        {% if upstairs_mode == 'temp' or downstairs_mode == 'temp' %}
        true
        {% else %}
        false
        {% endif %}
  action: 
    - service: notify.telegram_notify_Greg
      data:
        message: >-
          {% set upstairs_mode = state_attr('climate.upstairs', 'preset_mode') %}
          {% set upstairs_set_temp = state_attr('climate.upstairs', 'target_temp_high') %}
          {% set downstairs_mode = state_attr('climate.downstairs', 'preset_mode') %}
          {% set downstairs_set_temp = state_attr('climate.downstairs', 'target_temp_high') %}
          The Upstairs Thermostat has been set to {{upstairs_mode}} ({{upstairs_set_temp}})
          and the Downstairs thermostat is set to {{downstairs_mode}} ({{downstairs_set_temp}}).
          Due to manual override, Automation: "Set to Home" is being disabled.
        data: 
          inline_keyboard: 
           - '/confirm?'
           - '/deny?'

- alias: 'Override Confirm'
  initial_state: true
  trigger: 
    platform: event
    event_type: telegram_callback
    event_data:
      command: '/confirm?'
  
  action:
    - service: automation.turn_off
      target:
        entity_id: automation.set_thermostats_to_home

    - service: telegram_bot.answer_callback_query
      data_template:
        callback_query_id: '{{ trigger.event.data.id }}'
        message: Disabling "Set Thermostats to Home"

- alias: 'Override Deny'
  initial_state: true
  trigger: 
    platform: event
    event_type: telegram_callback
    event_data:
      command: '/deny?'
  
  action:
    - service: telegram_bot.answer_callback_query
      data_template:
        callback_query_id: '{{ trigger.event.data.id }}'
        message: Ignoring manual temperature set.
- alias: Reset Thermostat Controls
  trigger: 
    platform: event
    event_type: telegram_command
    event_data:
      command: '/reset_thermostats'
  action: 
    - service: telegram_bot.send_message
      data: 
        chat_id: '{{ trigger.event.data.chat_id }}'
        message: "Resetting Thermostat States"
    - service: automation.turn_on
      target:
        entity_id:
          - automation.set_thermostats_to_home
          - automation.set_thermostats_to_away