# - alias: "Trash Notify"
#   trigger:
#     - platform: state
#       entity_id: binary_sensor.trash_day
#       to: 'on'
#   action:
#     - service: notify.telegram_notify_Sara
#       data:
#         message: "Tomorrow's Trash Day, don't forget to take out the trash"
#     - service: notify.telegram_notify_Greg
#       data:
#         message: "Tomorrow's Trash Day, don't forget to take out the trash"

# - alias: "Recycle Notify"
#   trigger:
#     - platform: state
#       entity_id: binary_sensor.recycle_day
#       to: 'on'
#   action:
#     - service: notify.telegram_notify_Sara
#       data:
#         message: "Tomorrow's Trash & *Recycle* Day, don't forget to take it out."
#     - service: notify.telegram_notify_Greg
#       data:
#         message: "Tomorrow's Trash & *Recycle* Day, don't forget to take it out."

- alias: "Trash/Recyle Notifier"
  trigger:
    - platform: template
      value_template: >-
        {% if is_state('binary_sensor.trash_day','on') 
          and  is_state('binary_sensor.recycle_day','off') %}
          true
        {% elif is_state('binary_sensor.trash_day','on') 
          and  is_state('binary_sensor.recycle_day','on') %}
          true
        {% else %}
          false
        {% endif %}
  action: 
    - service: notify.telegram_notify_Greg
      data:
        message: >-
          {% if is_state('binary_sensor.trash_day','on') 
            and  is_state('binary_sensor.recycle_day','off') %}
            Tomorrow's Trash Day, don't forget to take it out.
          {% elif is_state('binary_sensor.trash_day','on') 
            and  is_state('binary_sensor.recycle_day','on') %}
            Tomorrow's Trash & *Recycle* Day, don't forget to take it out.
          {% endif %}


