---
name: Lint Code Base
on:
  push:
  pull_request:
    branches: [master]

jobs:
  build:
    name: Lint Code Base
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2
      - name: Super-Linter
        uses: github/super-linter:slim-v4
        
        env:
          SUPPRESS_POSSUM: true
          GITHUB_TOKEN: ${{ secrets.GH_ACTIONS_TOKEN }}
          #JSCPD_CONFIG_FILE: .jspcd.json